
name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions/checkout@v3
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Build
        run: cargo build --verbose
      - name: Compile
        run: cargo nextest run --no-run --locked
      - name: Test
        run: cargo nextest run --verbose
      - name: Audit
        run: cargo audit
